/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skillfrog.Frames;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.List;
import java.util.ArrayList;
import skillfrog.Quiz;
import skillfrog.StudentService;

/**
 *
 * @author Enter Computer
 */
public class QuizFrame extends javax.swing.JFrame {
    private int studentId;
    private int lessonId;
    private int courseId;
    private StudentService studentService;
    private List<String> questions;
    private List<List<String>> options;
    private JPanel container;
    private ButtonGroup[] buttonGroups;

    /**
     * Creates new form QuizFrame
     */
     public QuizFrame(int studentId, int lessonId, StudentService studentService, int courseId) {
        this.studentId = studentId;
        this.lessonId = lessonId;
        this.studentService = studentService;
        this.courseId = courseId;

        Quiz quiz = studentService.getQuiz(lessonId);
        if (quiz == null) {
            JOptionPane.showMessageDialog(this, "No quiz available for this lesson!");
            dispose();
            return;
        }
        this.questions = quiz.getQuestions();
        this.options = quiz.getOptions();

        initUI();
    }

    private void initUI() {
        setTitle("Lesson Quiz");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        container = new JPanel();
        container.setLayout(new BoxLayout(container, BoxLayout.Y_AXIS));

        buttonGroups = new ButtonGroup[questions.size()];

        for (int i = 0; i < questions.size(); i++) {
            JPanel qPanel = new JPanel();
            qPanel.setLayout(new BoxLayout(qPanel, BoxLayout.Y_AXIS));
            qPanel.setBorder(BorderFactory.createTitledBorder("Q" + (i + 1)));

            JLabel qLabel = new JLabel(questions.get(i));
            qPanel.add(qLabel);

            ButtonGroup group = new ButtonGroup();
            buttonGroups[i] = group;

            List<String> opts = options.get(i);
            for (int j = 0; j < opts.size(); j++) {
                JRadioButton rb = new JRadioButton(opts.get(j));
                rb.setActionCommand(String.valueOf(j));
                group.add(rb);
                qPanel.add(rb);
            }

            container.add(qPanel);
        }

        JScrollPane scroll = new JScrollPane(container);
        add(scroll, BorderLayout.CENTER);

        JButton submitBtn = new JButton("Submit Quiz");
        submitBtn.addActionListener(e -> submitQuiz());
        add(submitBtn, BorderLayout.SOUTH);
    }

    private void submitQuiz() {
        List<Integer> answers = new ArrayList<>();
        for (ButtonGroup bg : buttonGroups) {
            if (bg.getSelection() == null) {
                JOptionPane.showMessageDialog(this, "Please answer all questions!");
                return;
            }
            answers.add(Integer.parseInt(bg.getSelection().getActionCommand()));
        }

        boolean passed = studentService.submitQuiz(studentId,courseId, lessonId, answers);
        String message = passed ? "Quiz Passed!" : "Quiz Failed!";
        JOptionPane.showMessageDialog(this, message);
        dispose();
    }
    public QuizFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
