/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package skillfrog;

import java.io.IOException;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

/**
 *
 * @author GAMING
 */
public class StyledPDF {

    public static void generatePDF(String name, String id, String level, String path) {
        try (PDDocument document = new PDDocument()) {

            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            PDPageContentStream content = new PDPageContentStream(document, page);

            // ----------- Title ------------
            content.beginText();
            content.setFont(PDType1Font.HELVETICA_BOLD, 28);
            content.newLineAtOffset(70, 750);
            content.showText("Student Enrollment Certificate");
            content.endText();

            // ----------- Line -------------
            content.setLineWidth(1);
            content.moveTo(50, 740);
            content.lineTo(550, 740);
            content.stroke();

            // ----------- Body -------------
            content.beginText();
            content.setFont(PDType1Font.HELVETICA, 14);
            content.newLineAtOffset(50, 700);
            content.setLeading(22);

            content.showText("This certifies that the following student is enrolled:");
            content.newLine();
            content.newLine();

            content.showText("Name: " + name);
            content.newLine();
            content.showText("ID: " + id);
            content.newLine();
            content.showText("Level: " + level);
            content.newLine();

            content.endText();

            // ----------- Table Box ---------
            float boxX = 40;
            float boxY = 610;
            float boxWidth = 520;
            float boxHeight = 120;

            content.setLineWidth(1.2f);
            content.addRect(boxX, boxY, boxWidth, boxHeight);
            content.stroke();

            // ----------- Table Text --------
            content.beginText();
            content.setFont(PDType1Font.HELVETICA, 13);
            content.newLineAtOffset(boxX + 15, boxY + 90);

            content.showText("Student Summary:");
            content.newLine();
            content.newLine();

            content.showText("• Name: " + name);
            content.newLine();
            content.showText("• ID: " + id);
            content.newLine();
            content.showText("• Level: " + level);

            content.endText();

            // ----------- Footer ------------
            content.beginText();
            content.setFont(PDType1Font.HELVETICA_OBLIQUE, 10);
            content.newLineAtOffset(220, 40);
            content.showText("Generated by Your Application");
            content.endText();

            content.close();

            document.save(path);

            System.out.println("PDF created successfully!");

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
